### ISSUE TITLE
Traceback error when attempting to merge a certain material

### ISSUE THREAD

**Issue by Luxiram** [Grim-es/material-combiner-addon#46]
I'm trying to atlas all of my materials and one of the materials keeps getting this traceback error, preventing it from being merged with the other textures

Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\material-combiner-addon-master\extend_lists.py", line 18, in draw_item
    mat_preview = item.mat.preview
AttributeError: 'NoneType' object has no attribute 'icon_id'

location: C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\material-combiner-addon-master\ui\main_menu.py:20

**Comment by 2theMAXtheStairFax** [comment]
![image](https://user-images.githubusercontent.com/50429100/178893573-8ba305be-fcd5-4eca-be34-aac3c5110a00.png)
 i get a similar error.

**Comment by Grim-es** [comment]
> ![image](https://user-images.githubusercontent.com/50429100/178893573-8ba305be-fcd5-4eca-be34-aac3c5110a00.png) i get a similar error.

Hello, you might be used an unsupported shader. You can view the file [utils/materials.py](https://github.com/Grim-es/material-combiner-addon/blob/master/utils/materials.py) to see what shaders are supported or what node names should be

**Comment by Grim-es** [comment]
> 

Should be fixed on latest update

**Comment by Grim-es** [comment]
> Python: Traceback (most recent call last):
File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\material-combiner-addon-master\extend_lists.py", line 18, in draw_item
mat_preview = item.mat.preview
AttributeError: 'NoneType' object has no attribute 'icon_id'

Should be fixed on latest update

**Comment by Susoy114514** [comment]
Keyerror: 'bpy_prop_collection[key]: key"Principled BSDF"not found'
Why I got this error when I using"Save Atlas to"

**Comment by Grim-es** [comment]
> Keyerror: 'bpy_prop_collection[key]: key"Principled BSDF"not found' Why I got this error when I using"Save Atlas to"

It appears that your Blender is not set to English, which results in a different `name` property on the shader node. Please change it to `Principled BSDF` for all materials and also update name of texture node that will be used in atlas process to `Image Texture` as well for all materials.
